name: wf_dev_pr
on:
  pull request:
    branches:
      - develop
jobs:
  pr_dev_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome step
        run: echo "Welcome to GITHUB ACTIONS!!!!!!!!"
      - name: job1 second step
        run: echo "This is the second step of job1"
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v6
        run: echo "This is the step of second job"